name: Comment on PR

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Allow Dependabot to modify the PR, forks should remain read-only
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Add comment to the PR
        id: notification
        run: |
           gh pr comment ${{ github.event.pull_request.number }} --body "This is a GitHub Actions test"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
